name: FULL_BUILD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
           sudo apt-get update && \
           sudo apt-get install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev \ 
           patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs \
           git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo npm libelf-dev clang flex bison g++ \
           g++-multilib python3-distutils rsync file wget

    - name: Run full build
      run: make FULL_BUILD=true

