name: FULL_BUILD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
           sudo sed -i "/deb-src/s/# //g" /etc/apt/sources.list
           sudo apt-get update
           sudo apt-get install -y build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev
           sudo apt-get install -y patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs
           sudo apt-get install -y git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo npm libelf-dev
           sudo apt-get install -y clang flex bison g++ g++-multilib python3-distutils rsync file wget
           sudo apt-get build-dep -y linux

    - name: Run full build
      run: make FULL_BUILD=true

